project-chip/certification-tool-backend

.vscode/settings.json

The `settings.json` file is missing in this repo after code migration.

Added missing settings.json file

---

app/crud/crud_test_run_execution.py

Replace private link with the public link

Replace private link with the public link

---

scripts/reset_db.py

Add support to reset db model for unit test purposes.

Add support to reset db for unit test

---

.version_information

Update backend version to `beta1.1 Spring 2024`
Issue: https://github.com/project-chip/certification-tool/issues/93

update backend version in FE

---

app/core/config.py

Update SDK commit SHA

---

.version_information

Updated to 2.10-beta2+spring2024

Update the TH version in UI to "2.10-beta2+spring2024"

---

test_collections/sdk_tests/support/python_testing/sdk_python_tests.py
test_collections/sdk_tests/support/tests/python_tests/test_python_script/TC_Sample.py
test_collections/sdk_tests/support/yaml_tests/sdk_yaml_tests.py

Omit tests suites that don't have any tests

Omit tests suites without any tests

---

.version_information
app/core/config.py
test_collections/sdk_tests/support/python_testing/models/python_test_parser.py

Updated version to 2.10-beta2.1+spring2024

Updated version to 2.10-beta2.1+spring2024

---

.version_information
test_collections/sdk_tests/support/python_testing/models/python_test_parser.py
test_collections/sdk_tests/support/python_testing/models/test_case.py

Updated backend version

---

test_collections/matter/sdk_tests/support/python_testing/models/utils.py
test_collections/matter/sdk_tests/support/tests/python_tests/test_utils.py

Increasing log level by enabling trace log

---

test_collections/matter/sdk_tests/support/python_testing/models/python_testing_hooks_proxy.py

Related  issue: https://github.com/project-chip/certification-tool/issues/214

Fixed step_skipped for python test

---

test_collections/matter/sdk_tests/support/python_testing/models/rpc_client/test_harness_client.py
test_collections/matter/sdk_tests/support/python_testing/models/test_case.py

Workaround for python test log handing.

Workaround for python test big log data

---

test_collections/matter/sdk_tests/support/python_testing/models/rpc_client/test_harness_client.py
test_collections/matter/sdk_tests/support/python_testing/models/test_case.py

- Fixes https://github.com/project-chip/certification-tool/issues/204

Fix custom SDK python tests

---

app/api/api_v1/endpoints/test_run_executions.py
app/log_utils.py
app/models/test_run_execution.py
test_collections/matter/sdk_tests/support/python_testing/models/test_case.py

Improve the download log performance
Related issue: https://github.com/project-chip/certification-tool/issues/226
PS: Maybe the target branch might change.

Improve download log performance

---

app/tests/api/api_v1/test_projects.py
app/tests/api/api_v1/test_test_run_executions.py
app/tests/crud/test_project.py
app/tests/crud/test_test_run_execution.py
app/tests/utils/test_run_execution.py
app/tests/utils/utils.py

Updated some unit test in order to avoid matter code dependency

Update unit tests to avoid matter code dependency

---

test_collections/matter/scripts/update-sample-apps.sh

Do not pull SDK image if it exists a local image

Do not pull SDK image if it exists a local image

---

test_collections/matter/scripts/update-sample-apps.sh

At this point we call docker using sudo to avoid docker errors

Fix update sample apps script

---

test_collections/matter/setup.sh

Remove 22.04 packages versions
TH PR: https://github.com/project-chip/certification-tool/pull/321

Ubuntu 22.04 is not more supported

---

test_collections/matter/sdk_tests/support/yaml_tests/matter_yaml_runner.py
test_collections/matter/sdk_tests/support/yaml_tests/models/chip_suite.py
test_collections/matter/test_environment_config.py

support wifipaf-wifi command for test harness

---

test_collections/matter/sdk_tests/support/python_testing/models/test_case.py

Fix python test steps handling

---

.version_information
test_collections/matter/config.py

v2.11-beta2+fall2024

---

.version_information
test_collections/matter/config.py

- v2.11-beta3+fall2024
- SDK SHA: 17b1a38e909e7874593bcb87c31be03a5866f1d4

Release v2.11-beta3+fall2024

---

test_collections/matter/sdk_tests/support/python_testing/models/python_test_parser.py

The goal of this PR is to add TC-IDM-10.5 to the mandatory suite
https://github.com/project-chip/certification-tool/issues/461

Add TC-IDM-10.5 test case to mandatory suite

---

test_collections/matter/sdk_tests/support/python_testing/models/test_suite.py
test_collections/matter/sdk_tests/support/tests/python_tests/test_python_test_suite.py

The Goal of this PR is to workaround the chip.testing files in inside chip-cert-bins container. 
https://github.com/project-chip/certification-tool/issues/473

Copy chip.testing files to local/lib folder

---

app/tests/api/api_v1/test_test_run_executions.py
test_collections/matter/config.py
test_collections/matter/sdk_tests/support/python_testing/models/rpc_client/test_harness_client.py
test_collections/matter/sdk_tests/support/python_testing/models/utils.py
test_collections/matter/sdk_tests/support/sdk_container.py

Updated references after python_testing sdk refactoring
https://github.com/project-chip/certification-tool/issues/478
Unit tests and UI passing

Update python_testing references after SDK refactoring

---

test_collections/matter/sdk_tests/support/python_testing/models/test_case.py
test_collections/matter/sdk_tests/support/sdk_container.py
test_collections/matter/sdk_tests/support/tests/test_sdk_container.py

[FIX] Intermittent Tests Start Error With No Information (#157)	316a934	antonio-amjr <116589331+antonio-amjr@users.noreply.github.com>	24 Oct 2024 at 09:47

Revert changes

---

test_collections/matter/scripts/update-pull-sdk-docker-image.sh
test_collections/matter/scripts/update-sample-apps.sh
test_collections/matter/setup.sh

- Extracted script to pull SDK docker image

01 - Isolate SDK docker pull script

---

app/test_engine/test_runner.py
app/tests/api/api_v1/test_test_run_executions_log.py
cspell.json

Add logs for project config

---

test_collections/matter/config.py
test_collections/matter/sdk_tests/support/python_testing/models/rpc_client/test_harness_client.py
test_collections/matter/sdk_tests/support/python_testing/models/utils.py
test_collections/matter/sdk_tests/support/sdk_container.py

Revert code changes related to SDK path refactoring, since the SDK refactoring was related to v1.5 version and v2.12 is related to 1.4.1 version.
Also, updated the SDK SHA.

Revert code changes related to SDK path refactoring

---

test_collections/matter/config.py
test_collections/matter/sdk_tests/python_tests_info.json

Updated SDK SHA and Python Tests JSON

Updated SDK SHA and Python Tests JSON

---

app/models/test_case_metadata.py

Removed unused count field at test_case_metadata

Removed unused count field at test_case_metadata

---

.version_information
test_collections/matter/config.py
test_collections/matter/sdk_tests/python_tests_info.json

This version adds the TSTAT 2 2  test case
https://github.com/project-chip/certification-tool/issues/531

Added TSTAT 2 2 test case

---

test_collections/matter/sdk_tests/support/python_testing/models/rpc_client/test_harness_client.py
test_collections/matter/sdk_tests/support/python_testing/models/utils.py
test_collections/matter/sdk_tests/support/sdk_container.py
test_collections/matter/sdk_tests/support/tests/test_sdk_container.py

What Changed
Redo code changes related to SDK path refactoring, once reverted for v1.4.1 release.

Redo code changes related to SDK path refactoring

---

cspell.json
test_collections/matter/sdk_tests/support/tests/yaml_tests/test_matter_yaml_runner.py
test_collections/matter/sdk_tests/support/yaml_tests/matter_yaml_runner.py
test_collections/matter/sdk_tests/support/yaml_tests/models/chip_test.py
test_collections/matter/sdk_tests/support/yaml_tests/sdk_yaml_tests.py

Fixed Custom YAML test execution.
https://github.com/project-chip/certification-tool/issues/560
- Unit Test passing
- Developer testing
Create a new test run execution with just the custom yaml script selected. TH will just display just one test to run.

[FIX] Fix Custom YAML test execution

---

app/api/api_v1/endpoints/projects.py
app/tests/api/api_v1/test_projects.py
app/utils.py
test_collections/matter/config.py

The goal of this PR is to implement to support to the project configuration for Platform Certification functionality
https://github.com/project-chip/certification-tool/issues/563
- Unit test added and passing
- Added PICS files along with dmp-test-skip.xml by Drag and Drop
- Added PICS files along with dmp-test-skip.xml by select dialog

Implement Project config changes due to platform certification support

---

.version_information
cspell.json
test_collections/matter/config.py

Changes for v2.13-beta4+summer2025 version

Changes for v2.13-beta4+summer2025 version

---

test_collections/matter/sdk_tests/support/performance_tests/models/performance_tests_hooks_proxy.py
test_collections/matter/sdk_tests/support/python_testing/models/python_testing_hooks_proxy.py
test_collections/matter/sdk_tests/support/tests/yaml_tests/test_matter_yaml_runner.py
test_collections/matter/sdk_tests/support/yaml_tests/matter_yaml_runner.py
test_collections/matter/sdk_tests/support/yaml_tests/models/chip_test.py

Updated SDK references after SDK refactoring 
https://github.com/project-chip/certification-tool/issues/618

Updated the affected sdk references

---

app/pics_applicable_test_cases.py
app/tests/api/api_v1/test_test_run_executions.py
app/tests/pics/test_applicable_test_cases_list.py

Fixed platform tests selection when no PICS were informed.
https://github.com/project-chip/certification-tool/issues/625
Unit Test added and running successfully

Fixed platform tests selection when no PICS were informed

---

cspell.json
test_collections/matter/sdk_tests/support/performance_tests/models/test_case.py
test_collections/matter/sdk_tests/support/performance_tests/scripts/sdk/TC_COMMISSIONING_1_0.py
test_collections/matter/sdk_tests/support/python_testing/models/rpc_client/test_harness_client.py

Changed the logic of iteractions inside TC_COMMISSIONING_1_0 test case. Current the stress test is running successfully with only 1 iteration.
TC_COMMISSIONING_1_0 test run successfully with more than 1 iteration

Fixed stress test interaction TC_COMMISSIONING_1_0 test case

---

app/api/api_v1/sockets/web_sockets.py
app/constants/websockets_constants.py
app/socket_connection_manager.py
app/tests/socket_connection_manager/test_socket_connection_manager.py
app/tests/user_prompts/test_options_select_user_prompts.py
app/tests/user_prompts/test_text_input_user_prompts.py
test_collections/matter/sdk_tests/support/chip/chip_server.py
test_collections/matter/sdk_tests/support/constants.py
test_collections/matter/sdk_tests/support/yaml_tests/models/test_case.py
test_collections/matter/sdk_tests/support/yaml_tests/models/yaml_test_parser.py

This PR adds the following:
- Handle socket operations for video stream in `SocketConnectionManager`.
- Add a timeout to prevent the UDP socket from occasionally waiting indefinitely on device disconnection

[Camera] Handle video stream socket operations in SocketConnectionManager

---

app/constants/websockets_constants.py
app/user_prompt_support/__init__.py
app/user_prompt_support/prompt_request.py
test_collections/matter/sdk_tests/support/python_testing/models/python_testing_hooks_proxy.py
test_collections/matter/sdk_tests/support/python_testing/models/test_case.py

This PR adds push av user prompt support in the backend to allow test cases to invoke and seek push av stream validation.

[Camera] Push AV validation prompt support
