- app/test_engine/models/manual_test_case.py
Add validation when getting a content line from uploaded file in `app/test_engine/models/manual_test_case.py`.
This is necessary because the uploaded file may contain char that are not decodable to utf-8.
https://github.com/project-chip/certification-tool/issues/49
Unit test 100% passed
> Add validation when getting a content line from uploaded file

- app/chip_tool/chip_tool.py
- app/chip_tool/test_suite.py
A fix for the following issue:
- https://github.com/project-chip/certification-tool/issues/40
Maybe a permanent solution should involve changes in the runner so that it doesn't stop automatically at every test run. In that case we wouldn't need to start and stop it every time we need to commission or decommission a device, we'd start it at the beginning of a test suite execution and stop it at the cleanup.
Since changes in the runner usually takes longer, we can have this temporary solution for TH now and then migrate to another solution involving the runner changes later.
> Fix decommissioning problem for simulated test cases

- test_collections/sdk_tests/support/paths.py
- test_collections/sdk_tests/support/yaml_tests/models/yaml_test_folder.py
- test_collections/sdk_tests/support/yaml_tests/sdk_yaml_tests.py
Since #10 and #14 was merged, we introduced a problem where the SDK tests only worked when running the backend in developer mode.
Specially, the problem stems from the fact that we used `/app/backed` hardcoded paths:
https://github.com/project-chip/certification-tool-backend/pull/10/files#diff-aea3c8e66d486bcaf287e7c19fa77772d3f40ac9733ee99c465657afda4104d5L41
And that only works in dev mode.
This PR changes this back to using relative paths.
> Fix problem with sdk_tests collection using hardcoded paths

- app/core/config.py
- app/otbr_manager/otbr_manager.py
This PR will change the default logging level to `info` as the logs get spammed with 1000 of debug lines from the zap xml parsing:
```
DEBUG    | 2023-11-09 19:16:11.606 | matter_idl.zapxml:endElement:75 | ELEMENT END: 'item'
DEBUG    | 2023-11-09 19:16:11.606 | matter_idl.zapxml:startElement:69 | ELEMENT START: 'item' / <xml.sax.xmlreader.AttributesImpl object at 0x7efc75dceef0>
DEBUG    | 2023-11-09 19:16:11.606 | matter_idl.zapxml:endElement:75 | ELEMENT END: 'item'
DEBUG    | 2023-11-09 19:16:11.607 | matter_idl.zapxml:startElement:69 | ELEMENT START: 'item' / <xml.sax.xmlreader.AttributesImpl object at 0x7efc75dceef0>
DEBUG    | 2023-11-09 19:16:11.607 | matter_idl.zapxml:endElement:75 | ELEMENT END: 'item'
DEBUG    | 2023-11-09 19:16:11.607 | matter_idl.zapxml:startElement:69 | …
```
> Set default log level to info, to eliminate chatter from python runner

- gunicorn/start.sh
- prestart.sh
This PR will fix the problem below, by ensuring that `prestart.sh` return a zero exit code on successful completion.
**Problem:**
`prestart.sh` will attempt to run `test_collection/<collection_name>/prestart.sh` if that script exists.
This is done by:
```bash
for dir in ./test_collections/*
do
prestart=$dir/prestart.sh
[ -x $prestart ] && $prestart
done
```
However, if the script doesn't exist. `[ -x $prestart ]`  will return a non-zero value.
As this is the last step in `prestart.sh` the exit code of `prestart.sh` will be the non-zero value if the last iteration in the for-loop is for a test_collection that doesn't have a prestart script.
This will stop the start.sh to not start the `gunicorn` server.
> Enforced exit code 0 in prestart.sh

- prestart.sh
Turned out #26 didn't actually work as the `exit 0` caused the parent script to exit due to this.
> Removed exit 0, as it exits the parent script

- app/constants/websockets_constants.py
- app/tests/user_prompts/test_options_select_user_prompts.py
- app/user_prompt_support/user_prompt_manager.py
Issue: [[Bug] The submit button is not appearing #60](https://github.com/project-chip/certification-tool/issues/60)
Frontend PR: [Missing submit button #14](https://github.com/project-chip/certification-tool-frontend/pull/14)
Missing submit button fixed, see frontend PR description for testing results.
> Missing submit button

- app/chip_tool/test_case.py
- app/constants/websockets_constants.py
- app/user_prompt_support/prompt_request.py
- app/user_prompt_support/user_prompt_manager.py
Issue: [[Bug] The submit button is not appearing #60](https://github.com/project-chip/certification-tool/issues/60)
* Proposal to add a new value for file uploads
* It needs to be aligned with the Frontend, as the new type will only work after updating the Frontend.
* Create a new Enum value for file upload request
* Prompt type refactor 
Frontend PR counterpart: [Missing submit button #15](https://github.com/project-chip/certification-tool-frontend/pull/15)
> Prompt request refactor

- app/chip_tool/chip_tool.py
The chip server is not stopping and TH is hanging while waiting for the process to exit.
This line had been added recently and I'm reverting it for now, since destroying the container will stop the server anyway. Later, I'll update the stop method to do it in another way that I've found that works.
I've run a `CHIP_TOOL` and a `CHIP_APP` test and they both finished the cleanup without hanging.
> Fix chip test cleanup hanging problem

- test_collections/sdk_tests/support/python_testing/models/test_case.py
- Added a test step for all SDK python tests to show the test case logs. We don't get the logs step by step, we only have it as a whole. That's why we're showing it complete at the end of the execution.
> Show python logs at the end of the test execution

- test_collections/sdk_tests/support/chip_tool/chip_tool.py
- test_collections/sdk_tests/support/python_testing/models/test_case.py
- test_collections/sdk_tests/support/python_testing/models/test_suite.py
- test_collections/sdk_tests/support/tests/python_tests/test_python_test_suite.py
- Started raising an exception if the commissioning fails in the test suite setup.
- Fixed the steps state after a failure happens during a python test. After the failure the test skips most of the following steps and then executes the last one, to show the logs.
- Commissioning error is reported and cancels the test suite execution.
- Test case steps' states after a failure.
- Test case that doesn't follow the template with errors on multiple tests
> Fix python tests error handling

- test_collections/sdk_tests/support/python_testing/models/python_test_models.py
- test_collections/sdk_tests/support/python_testing/models/python_test_parser.py
- test_collections/sdk_tests/support/python_testing/models/rpc_client/test_harness_client.py
- test_collections/sdk_tests/support/python_testing/models/test_case.py
- test_collections/sdk_tests/support/python_testing/sdk_python_tests.py
- test_collections/sdk_tests/support/tests/python_tests/test_python_parser.py
- test_collections/sdk_tests/support/tests/python_tests/test_python_test_case.py
- test_collections/sdk_tests/support/tests/python_tests/test_python_test_declarations.py
- Modified the python tests parser to separate each test case from a single python script. They are now shown individually in the UI and can be run separately.
- I modified a python script to follow the template and provide the test steps for the tests contained in the file.
- I ran the test cases in debug mode and manually performed a factory reset between each test execution to be able to pass most of these tests (a fix for this will be developed soon).
> Support multi-test scripts

- app/test_engine/models/test_case.py
- test_collections/sdk_tests/support/python_testing/models/test_case.py
- test_collections/sdk_tests/support/python_testing/models/test_suite.py
- test_collections/sdk_tests/support/yaml_tests/models/test_case.py
- test_collections/sdk_tests/support/yaml_tests/models/test_suite.py
Fix custom tests in place of sdk tests
https://github.com/project-chip/certification-tool/issues/133
SDK Python Test running (TC-ACE-1.3)
Custom Python Test running (TC-ACE-1.3)
- Unit test passing
> Fix custom tests in place of sdk tests

- test_collections/sdk_tests/support/models/matter_test_models.py
- test_collections/sdk_tests/support/python_testing/models/python_test_models.py
- test_collections/sdk_tests/support/python_testing/models/python_test_parser.py
- test_collections/sdk_tests/support/python_testing/models/test_case.py
- test_collections/sdk_tests/support/python_testing/models/test_suite.py
- test_collections/sdk_tests/support/python_testing/models/utils.py
- test_collections/sdk_tests/support/python_testing/sdk_python_tests.py
- test_collections/sdk_tests/support/tests/python_tests/test_python_test_case.py
- test_collections/sdk_tests/support/tests/python_tests/test_python_test_declarations.py
- test_collections/sdk_tests/support/tests/python_tests/test_python_test_suite.py
- test_collections/sdk_tests/support/tests/python_tests/test_sdk_python_collection.py
- test_collections/sdk_tests/support/tests/python_tests/test_utils.py
- test_collections/sdk_tests/support/utils.py
- Separated the SDK Python tests in 3 suites:
- Python Testing Suite: test cases that follow the template and need commissioning.
- Python Testing Suite - No commissioning: test cases that follow the template and don't need commissioning.
- Python Testing Suite - Legacy: test cases that don't follow the template so we don't know if they need commissioning or not.
- This change allows for running tests from different suites and collections in a single test run.
- "Make sure the DUT is in Commissioning Mode"
- Shown at:
- Setup for the "Python Testing Suite" suite.
- Setup for each test case of the "Python Testing Suite - No commissioning" and the "Python Testing Suite - Legacy" suites.
- "Should the DUT be commissioned to run this test case?"
- Shown at:
- Setup for each test case of the …
> Separate SDK Python tests in 3 suites and support running multiple suites/collections in one run

- app/api/api_v1/endpoints/projects.py
- app/tests/api/api_v1/test_projects.py
- The goal of this PR is perform a validation for the valid dut config properties when creating or updating a project.
Before this PR, if the user inputs an invalid dut config property, the UI shows a false positive message stating the change was performed successfully but in the end the change does not happened.
https://github.com/project-chip/certification-tool/issues/119
- Development testing using an invalid property inside dut_config
- Unit test added and passed
factoring
> Added checking for valid dut config properties 

- app/container_manager/container_manager.py
- app/test_engine/test_collection_discovery.py
- app/tests/conftest.py
- app/tests/test_engine/test_collection_discovery.py
- cspell.json
- test_collections/sample_tests/__init__.py
- test_collections/tool_blocklist_unit_tests/__init__.py
- test_collections/tool_unit_tests/__init__.py
- Created test collection objects on collection folder init files.
- Renamed "python_tests" collection to "Onboarding Payload Tests".
- Updated code around test collection discovery to stop automatically creating a collection from a subfolder of "test_collections" and only look for `TestCollectionDeclaration` objects.
- To facilitate the collections migration to the program folder.
- Collection "Onboarding Payload Tests" was discovered correctly.
There are changes in the python_tests submodule. So, before this PR can be merged, the following one must be merged and then the submodule SHA must be updated:
- https://github.com/project-chip/matter-test-scripts/pull/108
> Create collections on init files

- test_collections/matter/sdk_tests/support/python_testing/models/python_test_parser.py
- test_collections/matter/sdk_tests/support/python_testing/models/test_case.py
The Goal of this PR is to undo the changes implemented in this PR: https://github.com/project-chip/certification-tool-backend/pull/61
> Undo workaround changes for python tests parser

- test_collections/matter/sdk_tests/support/python_testing/models/python_testing_hooks_proxy.py
- test_collections/matter/sdk_tests/support/python_testing/models/test_case.py
- test_collections/matter/sdk_tests/support/yaml_tests/models/chip_test.py
- Added support for manual operations in SDK Python Tests.
- https://github.com/project-chip/certification-tool/issues/163
> Add support for manual operations in SDK Python Tests

- app/schemas/test_environment_config.py
- default_test_environment.config
- test_collections/matter/sdk_tests/support/python_testing/models/utils.py
- test_collections/matter/sdk_tests/support/tests/python_tests/test_utils.py
The Goal of this PR is to make trace-log configurable for Python Tests.
Related Issue: https://github.com/project-chip/certification-tool/issues/196
This PR does not fix this issue, it's actually a working around since by disabling trace-log the tests listed in the issue passes successfully.
> Make trace-log configurable

- test_collections/matter/sdk_tests/support/python_testing/sdk_python_tests.py
Reword python test legacy collection
https://github.com/project-chip/certification-tool/issues/216
Python test legacy collection reword in UI
Unit testing passing
> Reword python test legacy collection

- alembic/versions/9df8004ad9bb_migrate_python_test_legacy_suite_.py
- app/crud/crud_project.py
- cspell.json
- test_collections/matter/sdk_tests/support/tests/matter/test_test_environment_config.py
- test_collections/matter/test_environment_config.py
The Goal of this PR is to provide a migration scripts since `Python Testing Suite - Legacy` python suite was renamed to `Python Testing Suite - Old`.
https://github.com/project-chip/certification-tool/issues/256
> Create migration scripts due to python legacy suite was renamed

- app/test_engine/models/test_case.py
- app/tests/test_engine/test_test_case.py
TH was not considering test_parameter if they are not defined in default_test_parameter.  The goal of this PR is to allow the add test_parameter other than the default_test_parameter defined in test cases.
> Implement project config test_parameter allow non default test parameters

- app/test_engine/models/test_case.py
- app/test_engine/models/test_step.py
- app/test_engine/models/test_suite.py
- app/test_engine/models/utils.py
- cspell.json
- Let's separate the test suites using a line `#### ... ####`
- Let's separate the test cases using a line `==== ... ====`
- Let's separate the test steps using a line `---- ... ----`
> Added log line sepator

- scripts/build-docker-image.sh
To build the multiarch image we need to use the buildx (experimental) command.
It is necessary to push the generated image in the same build command.
We can improve this script structure in another PR.
> update build script

- cspell.json
- test_collections/matter/sdk_tests/support/python_testing/models/python_test_parser.py
- Adding default string when failed to parse the test step name
> fix python test step parser

- test_collections/matter/scripts/update-sample-apps.sh
Workaround for  https://github.com/project-chip/certification-tool/issues/315
The definite solution involves a change in the SDK Dockerfile and should only be implemented in TH when updating the SDK's SHA.
> Workaround for Matter update-sample-apps script bug

- test_collections/matter/sdk_tests/support/chip/chip_server.py
The goal of this PR is to workaround the SDK issue that happens while TH reads logs from chip-tool.
The SDK issue impacts YAMLS test execution.
SDK Issue: https://github.com/project-chip/connectedhomeip/issues/34237
##$ Testing
YAML test cases running successfully
> [FIX] Add workaround code for truncated log

- alembic/versions/e2c185af1226_pics_v2_support.py
- app/test_engine/models/test_run.py
- app/test_engine/models/test_suite.py
- test_collections/matter/sdk_tests/support/python_testing/models/test_case.py
- test_collections/matter/sdk_tests/support/yaml_tests/models/test_suite.py
Part of the PICS v2 implementation.
- Cancel test execution if one of the mandatory test cases fail on certification mode.
- Display a prompt explaining this cancellation to the user.
- Ask the user if the DUT should be commissioned at the start of each mandatory test case.
> Cancel test execution if one of the mandatory test cases fail on certification mode

- app/utils.py
Fixing the repeat feature for executions that have tests with two or more iterations.
Before this change, if any test from the execution had more iterations, only one iteration was being run.
Now all iterations are being respected in the repeat
> [FIX] TH Repeat Tests Feature With More Iterations

- test_collections/matter/sdk_tests/support/python_testing/models/python_test_parser.py
The python test parser is crashing when the SDK SHA is updated. With these changes, any exception that happens while retrieving the test description, steps or PICS are ignored so that the TH's backend does't crash and a warning is logged.
> Fix python test parsing crash

- test_collections/matter/sdk_tests/support/python_testing/models/python_testing_hooks_proxy.py
- test_collections/matter/sdk_tests/support/python_testing/models/test_case.py
- test_collections/matter/sdk_tests/support/yaml_tests/models/chip_test.py
Update the SDK start hooks and related methods with the steps parameter from the latest SDK version
With this current version of SDK, **Python Tests** fails receiving an extra unexpected parameter `steps`:
This change adds the `steps` parameter correcting this problem:
> [FIX] Update SDK Hooks With New Parameter

- app/models/test_enums.py
- app/test_engine/models/test_case.py
- app/test_engine/models/test_run.py
- app/test_engine/models/test_suite.py
- app/tests/test_engine/test_runner.py
- app/tests/test_log_utils.py
- test_collections/matter/config.py
- test_collections/matter/sdk_tests/support/python_testing/models/python_testing_hooks_proxy.py
- test_collections/matter/sdk_tests/support/python_testing/models/test_case.py
- test_collections/matter/sdk_tests/support/yaml_tests/models/chip_suite.py
- test_collections/tool_unit_tests/test_suite_expected/tctr_expected_case_not_applicable/__init__.py
- test_collections/tool_unit_tests/test_suite_expected/tctr_expected_case_not_applicable/tctr_expected_case_not_applicable.py
- test_collections/tool_unit_tests/test_suite_expected/test_suite_expected_2.py
Changes:
- Add support for new hooks method `test_skipped`.
- Update hooks'  method `test_start` to support new parameter.
- Handle state `NOT_APPLICABLE` for test cases, suites and runs.
- Improve logic to move to next step in python tests (at the start of the step instead of the end of the previous one).
- Add prompt to ask the user to make sure that the DUT is in commissioning mode at the start of a YAML chip tool test suite execution.
- Add and update unit tests.
> Add support for test not applicable

- cspell.json
- test_collections/matter/sdk_tests/support/python_testing/models/utils.py
- test_collections/matter/sdk_tests/support/tests/python_tests/test_utils.py
- test_collections/matter/sdk_tests/support/yaml_tests/models/chip_suite.py
Fix issue with commissioning when setting manual-code parameter
> Use manual-code or discriminator and password, never all of them

- app/test_engine/models/test_case.py
- app/test_engine/models/test_run.py
- app/test_engine/models/test_suite.py
- test_collections/matter/sdk_tests/support/python_testing/models/test_case.py
- test_collections/matter/sdk_tests/support/python_testing/models/test_suite.py
- test_collections/matter/sdk_tests/support/tests/python_tests/test_python_test_suite.py
- test_collections/matter/test_environment_config.py
- test_collections/tool_unit_tests/test_suite_chip/tctr_chip_log_parsing/tctr_chip_log_parsing.py
The test environment config is saved as a dictionary, but the type annotation is using TestEnvironmentConfig.
I ran some python tests, that ran with the correct parameters and all unit tests are passing.
> Fix project config type

- .version_information
- test_collections/matter/config.py
- test_collections/matter/sdk_tests/support/python_testing/models/utils.py
- test_collections/matter/test_environment_config.py
Add checking when qr-code parameter is informed, so it is not necessary to use discriminator and passcode. 
This implementation follows the manual-code handling. This now will fix the DUT commissioning when qr-code parameter is informed.
https://github.com/project-chip/certification-tool/issues/358
https://github.com/project-chip/certification-tool/issues/348
Unit test passed and TH is now able to commission device
> [FIX] Handle qr-code parameter

- app/test_engine/models/test_step.py
Changed in the code where to assign step status FAILED and ERROR. 
There is a scenario that for a single step it was receiving 2 calls from the hooks (`test_skipped` and `step_failure`) and the TH was reporting, at the end of the execution, a wrong test state and run state.
https://github.com/project-chip/certification-tool/issues/355
Unit test passed and TH Fails test case when a step Fails.
> [FIX] Handle ERROR and FAILED step states

- test_collections/matter/scripts/update-sample-apps.sh
Since a new fabric app was added into cert bin image, it was necessary to change the way to copy SDK fabric apps to host.
SDK PR that adds a new fabric app: https://github.com/project-chip/connectedhomeip/pull/35367
> Update the way to copy fabric apps at update-sample-apps script

- app/container_manager/container_manager.py
- test_collections/matter/sdk_tests/support/chip/chip_server.py
Added force remove and after container be destroyed.
https://github.com/project-chip/certification-tool/issues/414
Unit test passing, and the TC-DRLK-2.1  is now passing
> [FIX] Force container removal at destroy

- test_collections/matter/scripts/OTBR/otbr_start.sh
Fixes: https://github.com/project-chip/certification-tool/issues/420
---
Reverting the OTBR start script to use variables.
It seems important for environments with multiples Thread networks that we could easily change the Thread parameters.
So we're reverting the script to use the BR_VARIANT once again so the main thread fields may be changed all at once.
Some comments and a step to stop an already running container will be kept.
> [FIX] Reverting the OTBR Start Script

- test_collections/matter/config.py
Updated SDK SHA for V2.11+fall2024 release - After SDK revert changes related to endpoint argument in hooks.
> Updated SDK SHA for V2.11+fall2024 release - after revert

- test_collections/matter/sdk_tests/support/python_testing/models/python_test_parser.py
> Do not error while parsing SDK python tests

- test_collections/matter/sdk_tests/support/python_testing/models/test_suite.py
- test_collections/matter/sdk_tests/support/utils.py
The goal of this PR is to add a checking when the user select FAILS the DUT commissioning prompt.
https://github.com/project-chip/certification-tool/issues/464
> Check user prompt answer FAILED for DUT commissioning

- test_collections/matter/sdk_tests/support/python_testing/models/test_case.py
The Goal of this PR is to handle properly the skip step hook for Legacy Python test cases (Old Script format).
https://github.com/project-chip/certification-tool/issues/415
> Handle Skip test hook for old script python test cases

- test_collections/matter/sdk_tests/support/python_testing/models/test_case.py
- test_collections/matter/sdk_tests/support/sdk_container.py
- test_collections/matter/sdk_tests/support/tests/test_sdk_container.py
Fixes: https://github.com/project-chip/certification-tool/issues/450
There's an intermittent problem when running many tests that the logs don't show any information on why the error occurred, as we can see in the image below:
After trying to reproduce while debugging, the error was isolated and points out to be Python's `BaseManager` that failed to connect since the address was already used:
It was noted afterwards that the TH was currently creating the `BaseManager` (object to share data between processes) every time a Python Test is started. Thus, resulting sometimes in this error when was creating a new manager.
The proposed solution moved the manager creation to the initialization of the SDK Container, occurring only once for test run. When a Python Test starts now it will only …
> [FIX] Intermittent Tests Start Error With No Information

- .gitignore
- app/tests/__init__.py
- app/tests/conftest.py
- app/tests/sdk_container_mock.py
- cspell.json
- test_collections/matter/sdk_tests/support/python_testing/list_python_tests_classes.py
- test_collections/matter/sdk_tests/support/python_testing/models/python_test_parser.py
- test_collections/matter/sdk_tests/support/python_testing/sdk_python_tests.py
- test_collections/matter/sdk_tests/support/tests/test_sdk_container.py
Updated the files related to custom python tests in order to the be in accordance with the changes with the way to retrieve test steps names.
https://github.com/project-chip/certification-tool/issues/484 
Unit test updated and passing
TH UI List the custom test case
TH UI execution runs successfully the Custom Python test case.
> Implemented changes for custom python test

- test_collections/matter/scripts/update-sample-apps.sh
The goal of this PR is to update the origin folder from SKA apps. All SDK apps are now located at /apps folders.
https://github.com/project-chip/certification-tool/issues/403
**Important:**
Do NOT merge this PR until this PR be merged: https://github.com/project-chip/connectedhomeip/pull/35700
> Update update-sample-apps script to copy apps from a new origin

- test_collections/matter/sdk_tests/support/python_testing/models/test_suite.py
- test_collections/matter/sdk_tests/support/python_testing/sdk_python_tests.py
- test_collections/matter/sdk_tests/support/yaml_tests/models/test_suite.py
Added custom text for custom suite at test selection screen. 
https://github.com/project-chip/certification-tool/issues/229
Custom suite are now being displayed in both test selection and test execution screens.
> Fix suite names for custom python tests

- test_collections/matter/sdk_tests/python_tests_info.json
- test_collections/matter/sdk_tests/support/python_testing/list_python_tests_classes.py
- test_collections/matter/sdk_tests/support/python_testing/models/rpc_client/test_harness_client.py
Fixed some python tests not listed
https://github.com/project-chip/certification-tool/issues/504
No issue are now being reported after code fix
> ###########################################################################
> ###############################   REPORT   ################################
> ###########################################################################
> >>>>>>>> Output JSON file: /app/backend/test_collections/matter/sdk_tests/python_tests_info.json
> >>>>>>>> Total of test functions: 191
> >>>>>>>> Total of invalid test functions (don't start with 'test_TC_'): 12
> Warning: File path: sdk/TC_DeviceBasicComposition  Class: TC_DeviceBasicComposition. Invalid test function: test_all_commands_reported_are_executable
> Warning: File path: sdk/TC_DeviceBasicComposition …
> Fixed some python tests not listed

- app/api/api_v1/endpoints/projects.py
- app/tests/api/api_v1/test_projects.py
Implement support to export/import project config
https://github.com/project-chip/certification-tool/issues/448
https://github.com/project-chip/certification-tool/issues/503
Service GET `api/v1/projects/{id}/export` is working
Service POST `api/v1/projects/import` is working
Unit test added and passing
> [Feature] Implement support to export project config

- app/pics_applicable_test_cases.py
- app/schemas/pics.py
Add support to consider Negative PICS, such as `!MCORE.DT_SW_COMP` as description in image bellow:
https://github.com/project-chip/certification-tool/issues/320
TC with Negative PICS is now being considered.
For example, TC-BIND-2.1, which has the following PICS configuration is now being considered:
`BIND.C: true`
`MCORE.ROLE.CONTROLLER: true`
`MCORE.DT_SW_COMP: false`
Unit Testing passing
> [FIX] Added support to negated PICS

- Dockerfile
Ubuntu 22.04 now requires node min version of 20. We need to upgrade the nodejs installation.
> Upgrade Backend Node to match base image requirements

- .gitignore
- app/container_manager/container_manager.py
- test_collections/matter/config.py
- test_collections/matter/sdk_tests/support/python_testing/models/test_case.py
- test_collections/matter/sdk_tests/support/python_testing/models/test_suite.py
- test_collections/matter/sdk_tests/support/python_testing/models/utils.py
- test_collections/matter/sdk_tests/support/sdk_container.py
- test_collections/matter/sdk_tests/support/tests/python_tests/test_python_test_case.py
- test_collections/matter/sdk_tests/support/tests/python_tests/test_python_test_suite.py
- test_collections/matter/sdk_tests/support/utils.py
- test_collections/matter/sdk_tests/support/yaml_tests/models/chip_suite.py
The goal of this PR is to store the commissioning information so the user will no have to factory reset their devices. The users will be prompted if they want to user the existing commissioning information. This affect the Python test cases.
https://github.com/project-chip/certification-tool/issues/456
- Unit Tests Added and all passing
- New prompt will be displayed when a previous commission was performed
> [Feature] DO NOT require commissioning every test

- app/api/api_v1/endpoints/test_run_executions.py
- app/crud/crud_test_run_execution.py
- app/schemas/test_run_execution.py
- app/tests/api/api_v1/test_test_run_executions.py
- app/tests/crud/test_test_run_execution.py
Implement the backend endpoint to rename a test run execution
**PUT** `api/v1/test_run_executions/{execution-id}/rename?new_execution_name={new-execution-name}`
**Important**: TODO frontend implementation
https://github.com/project-chip/certification-tool/issues/460
> Implement rename test run execution name

- test_collections/matter/sdk_tests/support/python_testing/models/utils.py
The goal of this PR is to check for storage-path when other arguments was set but storage-path.
> Fix the checking for storage-path

- test_collections/matter/sdk_tests/scripts/fetch_sdk_tests_and_runner.sh
Starting the backend service of TH without access to the internet results in failure due to the `prestart.sh `script ran on the initialization. That happens because the pip command try to install the necessary wheels files from the project but try to search any dependency required online.
This solution changes the pip command to install without the dependencies if the current version of test yaml and SDK are up to date.
> [FIX] Starting Backend Without Internet Access

- .version_information
- test_collections/matter/sdk_tests/support/python_testing/models/test_case.py
- test_collections/matter/sdk_tests/support/python_testing/models/test_suite.py
- test_collections/matter/sdk_tests/support/tests/python_tests/test_python_test_case.py
- test_collections/matter/sdk_tests/support/tests/python_tests/test_python_test_suite.py
The Goal of this PR if to refactor the prompt displays or recommissioning feature.
Unit Tests Running 100%
Development Testing
`Recommissioning` dialog is now being displayed before `DUT In commissioning Mode` Prompt.
The changes affect both `Python Testing Suite` and  `Python Testing Suite - Old script format` suites
> Refatoring prompts for recommissioning

- test_collections/matter/sdk_tests/support/yaml_tests/models/test_suite.py
The goal of this PR is to remove commissioning information when running YAML scripts, since the pior commissioning information stored in TH is no longer valid when running YAML tests.
- Unit Tests running successfully
- Developer test:
Perform the following steps:
1.  Start a python test execution.
2. Start a YAML test execution.
3. Start a python test execution.
**Expected result**: The prompt asking to reuse commissioning information is not presented since the file was removed at step 2 (Start a YAML test execution)
> Remove commissioning information when running YAML scripts

- .version_information
- test_collections/matter/sdk_tests/support/python_testing/models/test_case.py
- test_collections/matter/sdk_tests/support/python_testing/models/test_suite.py
- test_collections/matter/sdk_tests/support/tests/python_tests/test_python_test_case.py
- test_collections/matter/sdk_tests/support/tests/python_tests/test_python_test_suite.py
- test_collections/matter/sdk_tests/support/yaml_tests/models/test_suite.py
Cherry picking two fixes related to the feature of "reusing the existing commissioning" that were included in the release `v.14.1` of TH.
Commits: https://github.com/project-chip/certification-tool-backend/pull/187 and https://github.com/project-chip/certification-tool-backend/pull/189.
> [Fix] Recommissioning Refactoring to V1.5

- .version_information
- test_collections/matter/scripts/update-sample-apps.sh
The goal of this PR is to workaround the copy of the app from container to host to also consider apps folder.
https://github.com/project-chip/certification-tool/issues/526
> Add apps folder when copying apps from container to host

- app/pics_applicable_test_cases.py
- app/test_engine/test_script_manager.py
- test_collections/matter/sdk_tests/support/performance_tests/sdk_performance_tests.py
Removing the Performance collection from PICS applicable tests validation.
This solves the issue from this TH version that using a **PICS** file results in auto-selecting the Performance test in background, even this collection not being visible in the "select tests" UI.
**Before:**
**After:**
> [FIX] Removing Performance Collection From PICS Validation

- test_collections/matter/config.py
- test_collections/matter/scripts/update-sample-apps.sh
Updated code to copy files from cert-bins image to host.
https://github.com/project-chip/certification-tool/issues/530
The mock_server folder is not available on host
> Copy mock_server from cert-bins to host

- cspell.json
- test_collections/matter/sdk_tests/support/python_testing/models/utils.py
- test_collections/matter/sdk_tests/support/tests/python_tests/test_utils.py
- test_collections/matter/sdk_tests/support/tests/yaml_tests/test_matter_yaml_runner.py
- test_collections/matter/sdk_tests/support/yaml_tests/matter_yaml_runner.py
- test_collections/matter/sdk_tests/support/yaml_tests/models/chip_suite.py
- test_collections/matter/test_environment_config.py
The goal of this PR is to revert the changes introduced in PR #185, which made the discriminator field optional for NFC thread pairing.
Unit tests have been updated accordingly and are all passing.
> Use discriminator for nfc thread

- test_collections/matter/sdk_tests/support/chip/chip_server.py
This change adds a fail-safe mechanism by including a timeout when stopping the chip server, after a test execution of YAML tests.
Currently the code uses a while loop that waits only to the exit code return for killing the chip server process in the SDK.
That may never happen, so this PRs included a timeout logic for the chip server exit.
> [FIX] Adding Timeout To Server Exit

- app/pics_applicable_test_cases.py
Added logs while TH is performing the logic to retrieves the eligible test cases.
https://github.com/project-chip/certification-tool/issues/586
- Logging DMP execution:
INFO     | 2025-05-05 13:58:43.233 | app.pics_applicable_test_cases:__handle_platform_certification:119 | Listing dmp_test_skip test cases: ['DLOG-2.1', 'TC-ACE-1.1', 'TC-ACE-1.2', 'TC-ACE-1.3', 'TC-ACE-1.4', 'TC-ACE-1.5', 'TC-ACE-1.6', 'TC-ACL-2.1', 'TC-ACL-2.10', 'TC-ACL-2.3', 'TC-ACL-2.4', 'TC-ACL-2.5', 'TC-ACL-2.6', 'TC-ACL-2.7', 'TC-ACL-2.8', 'TC-ACL-2.9', 'TC-BDX-1.2', 'TC-BDX-1.4', 'TC-BDX-2.1', 'TC-BDX-2.2', 'TC-CADMIN-1.10', 'TC-CADMIN-1.11', 'TC-CADMIN-1.13', 'TC-CADMIN-1.14', 'TC-CADMIN-1.15', 'TC-CADMIN-1.16', 'TC-CADMIN-1.19', 'TC-CADMIN-1.20', 'TC-CADMIN-1.21', 'TC-CADMIN-1.22', 'TC-CADMIN-1.23', …
> Added logs for applicable test cases

- test_collections/matter/sdk_tests/support/yaml_tests/models/chip_test.py
Fix: https://github.com/project-chip/certification-tool/issues/592
---
Adding the missing parameter to avoid the python's posicional argument error as described in the `[issue#592](https://github.com/project-chip/certification-tool/issues/592)`:
> Test Step Error: Error occurred during execution of test case TC-DGETH-2.2. ChipTest.step_manual() takes 1 positional argument but 2 were given.
> [FIX] Adding Step Manual Missing Parameter

- app/pics_applicable_test_cases.py
The goal of this PR is to fix the logic in a way to consider some tests with suffix (ex: `Semi-automated` ) that are not being considered.
https://github.com/project-chip/certification-tool/issues/582
All unit tests passing
Development testing: TC-CADMIN-1.6 (Semi-automated) test are now being selected as TC-CADMIN-1.6 is listed in `platform-test.json` file
> Fixed some platform tests not being added to applicable test cases

- app/pics_applicable_test_cases.py
- app/tests/pics/test_applicable_test_cases_list.py
- test_collections/matter/sdk_tests/support/performance_tests/sdk_performance_tests.py
- test_collections/matter/sdk_tests/support/performance_tests/utils.py
Fixing the linter's long line format error pointed by Github's CI.
The Stress Test variables were moved to the `utils.py` file as there seems more appropriate to store constants.
Also, fixing the CI removing two platform unit tests with issues.
Th following issue was created to fix and return those unit tests once again:
https://github.com/project-chip/certification-tool-backend/issues/222
> [Fix] Linter Error

- app/pics_applicable_test_cases.py
- app/tests/pics/test_applicable_test_cases_list.py
The goal of this PR is to fix the test selection logic for platform certification execution.
Only the tests listed in the platform test list file should be considered when the PLAT.CERT PICS PICS is set.
https://github.com/project-chip/certification-tool/issues/625
Unit tests updated and passing
> [FIX] Fix logic for platform tests selection

- test_collections/matter/sdk_tests/support/python_testing/models/python_test_parser.py
The goal of this PR is to make python script test name more flexible, so the user may define the test script using `TC_` or not.
https://github.com/project-chip/certification-tool/issues/624
Unit Test passing
TC-MOD-1.2 is not listed inside SDK Python Tests collection
> [FIX] Make python script test name more flexible

- app/pics_applicable_test_cases.py
The goal of this PR is to fix the logic for platform test selection in a way to consider both mandatory and non mandatory tests.
https://github.com/project-chip/certification-tool/issues/625
After uploadING some PICS the UI is now selecting mandatories and non mandatories Test
> [FIX] Fix logic for platform test selection

- app/tests/version/test_read_test_harness_backend_version.py
The unit tests were refactored to prevent them from modifying the .version_information file.
https://github.com/project-chip/certification-tool/issues/720
Run the full suite of unit tests and verify that the .version_information file remains unchanged.
> Updated unit test to not modify .version_information file

- app/api/api_v1/endpoints/test_run_executions.py
- app/tests/api/api_v1/test_test_run_executions.py
The goal of this PR is to add support to attach a cli execution into an existing project. 
https://github.com/project-chip/certification-tool/issues/714
- New unit tests were added and all unit test as running successfully.
- Run cli execution passing project-id argument
> ubuntu@ubuntu:~/certification-tool/cli$ ./cli.sh run-tests --tests-list TC-ACE-1.3 -p pics_tst --project-id 5
> Read config from file: {'network': {'fabric_id': '0', 'thread': {'dataset': {'channel': '15', 'panid': '0x1234', 'extpanid': '1111111122222222', 'networkkey': '00112233445566778899aabbccddeeff', 'networkname': 'DEMO'}, 'rcp_serial_path': '/dev/ttyACM0', 'rcp_baudrate': '115200', 'on_mesh_prefix': 'fd11:22::/64', 'network_interface': 'eth0'}, 'wifi': {'ssid': 'testharness', 'password': 'wifi-password'}}, …
> Added support to project_id in test_run_executions POST /cli

- test_collections/matter/config.py
- test_collections/matter/sdk_tests/scripts/fetch_sdk_tests_and_runner.sh
- test_collections/matter/sdk_tests/support/python_testing/models/rpc_client/test_harness_client.py
- test_collections/matter/sdk_tests/support/yaml_tests/matter_yaml_runner.py
- test_collections/matter/sdk_tests/support/yaml_tests/models/chip_test.py
Updated TH after SDK refactoring
https://github.com/project-chip/certification-tool/issues/734
TH launches successfully 
Unit tests running successfully
> [FIX] Updated TH after SDK refactoring

- cspell.json
- test_collections/matter/sdk_tests/scripts/fetch_sdk_tests_and_runner.sh
The goal of this PR is to fix another uncovered scenario in the initial PR. The execution was working only for the 1st execution because prestart script was not installing the python module, so this PR make the chipyaml module an installable package.
https://github.com/project-chip/certification-tool/issues/734
TH launches successfully not only in the 1st execution
```
Successfully installed chipyaml-0.0.1 matter-idl-1.0.0 matter-yamltests-1.0.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
+ exit 0
Prestart Complete
```
> Updated fetch_sdk_tests_and_runner script to install chipyaml wheel
